// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datamodel.proto

package com.ayon.movieservice.movieregistration;

public final class MovieRegistrationDatamodel {
  private MovieRegistrationDatamodel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MovieRegistrationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ayon.movieservice.movieregistration.MovieRegistration)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string imdbId = 2;</code>
     */
    java.lang.String getImdbId();
    /**
     * <code>string imdbId = 2;</code>
     */
    com.google.protobuf.ByteString
        getImdbIdBytes();

    /**
     * <code>int32 availableSeats = 3;</code>
     */
    int getAvailableSeats();

    /**
     * <code>string screenId = 4;</code>
     */
    java.lang.String getScreenId();
    /**
     * <code>string screenId = 4;</code>
     */
    com.google.protobuf.ByteString
        getScreenIdBytes();

    /**
     * <code>string movieTitle = 5;</code>
     */
    java.lang.String getMovieTitle();
    /**
     * <code>string movieTitle = 5;</code>
     */
    com.google.protobuf.ByteString
        getMovieTitleBytes();
  }
  /**
   * Protobuf type {@code com.ayon.movieservice.movieregistration.MovieRegistration}
   */
  public  static final class MovieRegistration extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ayon.movieservice.movieregistration.MovieRegistration)
      MovieRegistrationOrBuilder {
    // Use MovieRegistration.newBuilder() to construct.
    private MovieRegistration(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MovieRegistration() {
      id_ = "";
      imdbId_ = "";
      availableSeats_ = 0;
      screenId_ = "";
      movieTitle_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MovieRegistration(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              imdbId_ = s;
              break;
            }
            case 24: {

              availableSeats_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              screenId_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              movieTitle_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.internal_static_com_ayon_movieservice_movieregistration_MovieRegistration_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.internal_static_com_ayon_movieservice_movieregistration_MovieRegistration_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration.class, com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMDBID_FIELD_NUMBER = 2;
    private volatile java.lang.Object imdbId_;
    /**
     * <code>string imdbId = 2;</code>
     */
    public java.lang.String getImdbId() {
      java.lang.Object ref = imdbId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imdbId_ = s;
        return s;
      }
    }
    /**
     * <code>string imdbId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getImdbIdBytes() {
      java.lang.Object ref = imdbId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imdbId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AVAILABLESEATS_FIELD_NUMBER = 3;
    private int availableSeats_;
    /**
     * <code>int32 availableSeats = 3;</code>
     */
    public int getAvailableSeats() {
      return availableSeats_;
    }

    public static final int SCREENID_FIELD_NUMBER = 4;
    private volatile java.lang.Object screenId_;
    /**
     * <code>string screenId = 4;</code>
     */
    public java.lang.String getScreenId() {
      java.lang.Object ref = screenId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        screenId_ = s;
        return s;
      }
    }
    /**
     * <code>string screenId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getScreenIdBytes() {
      java.lang.Object ref = screenId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        screenId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MOVIETITLE_FIELD_NUMBER = 5;
    private volatile java.lang.Object movieTitle_;
    /**
     * <code>string movieTitle = 5;</code>
     */
    public java.lang.String getMovieTitle() {
      java.lang.Object ref = movieTitle_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        movieTitle_ = s;
        return s;
      }
    }
    /**
     * <code>string movieTitle = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMovieTitleBytes() {
      java.lang.Object ref = movieTitle_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        movieTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getImdbIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, imdbId_);
      }
      if (availableSeats_ != 0) {
        output.writeInt32(3, availableSeats_);
      }
      if (!getScreenIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, screenId_);
      }
      if (!getMovieTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, movieTitle_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getImdbIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, imdbId_);
      }
      if (availableSeats_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, availableSeats_);
      }
      if (!getScreenIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, screenId_);
      }
      if (!getMovieTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, movieTitle_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration)) {
        return super.equals(obj);
      }
      com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration other = (com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getImdbId()
          .equals(other.getImdbId());
      result = result && (getAvailableSeats()
          == other.getAvailableSeats());
      result = result && getScreenId()
          .equals(other.getScreenId());
      result = result && getMovieTitle()
          .equals(other.getMovieTitle());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + IMDBID_FIELD_NUMBER;
      hash = (53 * hash) + getImdbId().hashCode();
      hash = (37 * hash) + AVAILABLESEATS_FIELD_NUMBER;
      hash = (53 * hash) + getAvailableSeats();
      hash = (37 * hash) + SCREENID_FIELD_NUMBER;
      hash = (53 * hash) + getScreenId().hashCode();
      hash = (37 * hash) + MOVIETITLE_FIELD_NUMBER;
      hash = (53 * hash) + getMovieTitle().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ayon.movieservice.movieregistration.MovieRegistration}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ayon.movieservice.movieregistration.MovieRegistration)
        com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistrationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.internal_static_com_ayon_movieservice_movieregistration_MovieRegistration_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.internal_static_com_ayon_movieservice_movieregistration_MovieRegistration_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration.class, com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration.Builder.class);
      }

      // Construct using com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        imdbId_ = "";

        availableSeats_ = 0;

        screenId_ = "";

        movieTitle_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.internal_static_com_ayon_movieservice_movieregistration_MovieRegistration_descriptor;
      }

      public com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration getDefaultInstanceForType() {
        return com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration.getDefaultInstance();
      }

      public com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration build() {
        com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration buildPartial() {
        com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration result = new com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration(this);
        result.id_ = id_;
        result.imdbId_ = imdbId_;
        result.availableSeats_ = availableSeats_;
        result.screenId_ = screenId_;
        result.movieTitle_ = movieTitle_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration) {
          return mergeFrom((com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration other) {
        if (other == com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getImdbId().isEmpty()) {
          imdbId_ = other.imdbId_;
          onChanged();
        }
        if (other.getAvailableSeats() != 0) {
          setAvailableSeats(other.getAvailableSeats());
        }
        if (!other.getScreenId().isEmpty()) {
          screenId_ = other.screenId_;
          onChanged();
        }
        if (!other.getMovieTitle().isEmpty()) {
          movieTitle_ = other.movieTitle_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object imdbId_ = "";
      /**
       * <code>string imdbId = 2;</code>
       */
      public java.lang.String getImdbId() {
        java.lang.Object ref = imdbId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          imdbId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string imdbId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getImdbIdBytes() {
        java.lang.Object ref = imdbId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imdbId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string imdbId = 2;</code>
       */
      public Builder setImdbId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imdbId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string imdbId = 2;</code>
       */
      public Builder clearImdbId() {
        
        imdbId_ = getDefaultInstance().getImdbId();
        onChanged();
        return this;
      }
      /**
       * <code>string imdbId = 2;</code>
       */
      public Builder setImdbIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        imdbId_ = value;
        onChanged();
        return this;
      }

      private int availableSeats_ ;
      /**
       * <code>int32 availableSeats = 3;</code>
       */
      public int getAvailableSeats() {
        return availableSeats_;
      }
      /**
       * <code>int32 availableSeats = 3;</code>
       */
      public Builder setAvailableSeats(int value) {
        
        availableSeats_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 availableSeats = 3;</code>
       */
      public Builder clearAvailableSeats() {
        
        availableSeats_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object screenId_ = "";
      /**
       * <code>string screenId = 4;</code>
       */
      public java.lang.String getScreenId() {
        java.lang.Object ref = screenId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          screenId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string screenId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getScreenIdBytes() {
        java.lang.Object ref = screenId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          screenId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string screenId = 4;</code>
       */
      public Builder setScreenId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        screenId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string screenId = 4;</code>
       */
      public Builder clearScreenId() {
        
        screenId_ = getDefaultInstance().getScreenId();
        onChanged();
        return this;
      }
      /**
       * <code>string screenId = 4;</code>
       */
      public Builder setScreenIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        screenId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object movieTitle_ = "";
      /**
       * <code>string movieTitle = 5;</code>
       */
      public java.lang.String getMovieTitle() {
        java.lang.Object ref = movieTitle_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          movieTitle_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string movieTitle = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMovieTitleBytes() {
        java.lang.Object ref = movieTitle_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          movieTitle_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string movieTitle = 5;</code>
       */
      public Builder setMovieTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        movieTitle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string movieTitle = 5;</code>
       */
      public Builder clearMovieTitle() {
        
        movieTitle_ = getDefaultInstance().getMovieTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string movieTitle = 5;</code>
       */
      public Builder setMovieTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        movieTitle_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.ayon.movieservice.movieregistration.MovieRegistration)
    }

    // @@protoc_insertion_point(class_scope:com.ayon.movieservice.movieregistration.MovieRegistration)
    private static final com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration();
    }

    public static com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MovieRegistration>
        PARSER = new com.google.protobuf.AbstractParser<MovieRegistration>() {
      public MovieRegistration parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MovieRegistration(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MovieRegistration> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MovieRegistration> getParserForType() {
      return PARSER;
    }

    public com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MovieRegisteredOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ayon.movieservice.movieregistration.MovieRegistered)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.ayon.movieservice.movieregistration.MovieRegistration movieregistration = 1;</code>
     */
    boolean hasMovieregistration();
    /**
     * <code>.com.ayon.movieservice.movieregistration.MovieRegistration movieregistration = 1;</code>
     */
    com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration getMovieregistration();
    /**
     * <code>.com.ayon.movieservice.movieregistration.MovieRegistration movieregistration = 1;</code>
     */
    com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistrationOrBuilder getMovieregistrationOrBuilder();
  }
  /**
   * Protobuf type {@code com.ayon.movieservice.movieregistration.MovieRegistered}
   */
  public  static final class MovieRegistered extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ayon.movieservice.movieregistration.MovieRegistered)
      MovieRegisteredOrBuilder {
    // Use MovieRegistered.newBuilder() to construct.
    private MovieRegistered(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MovieRegistered() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MovieRegistered(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration.Builder subBuilder = null;
              if (movieregistration_ != null) {
                subBuilder = movieregistration_.toBuilder();
              }
              movieregistration_ = input.readMessage(com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(movieregistration_);
                movieregistration_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.internal_static_com_ayon_movieservice_movieregistration_MovieRegistered_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.internal_static_com_ayon_movieservice_movieregistration_MovieRegistered_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered.class, com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered.Builder.class);
    }

    public static final int MOVIEREGISTRATION_FIELD_NUMBER = 1;
    private com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration movieregistration_;
    /**
     * <code>.com.ayon.movieservice.movieregistration.MovieRegistration movieregistration = 1;</code>
     */
    public boolean hasMovieregistration() {
      return movieregistration_ != null;
    }
    /**
     * <code>.com.ayon.movieservice.movieregistration.MovieRegistration movieregistration = 1;</code>
     */
    public com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration getMovieregistration() {
      return movieregistration_ == null ? com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration.getDefaultInstance() : movieregistration_;
    }
    /**
     * <code>.com.ayon.movieservice.movieregistration.MovieRegistration movieregistration = 1;</code>
     */
    public com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistrationOrBuilder getMovieregistrationOrBuilder() {
      return getMovieregistration();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (movieregistration_ != null) {
        output.writeMessage(1, getMovieregistration());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (movieregistration_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMovieregistration());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered)) {
        return super.equals(obj);
      }
      com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered other = (com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered) obj;

      boolean result = true;
      result = result && (hasMovieregistration() == other.hasMovieregistration());
      if (hasMovieregistration()) {
        result = result && getMovieregistration()
            .equals(other.getMovieregistration());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMovieregistration()) {
        hash = (37 * hash) + MOVIEREGISTRATION_FIELD_NUMBER;
        hash = (53 * hash) + getMovieregistration().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ayon.movieservice.movieregistration.MovieRegistered}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ayon.movieservice.movieregistration.MovieRegistered)
        com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegisteredOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.internal_static_com_ayon_movieservice_movieregistration_MovieRegistered_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.internal_static_com_ayon_movieservice_movieregistration_MovieRegistered_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered.class, com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered.Builder.class);
      }

      // Construct using com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (movieregistrationBuilder_ == null) {
          movieregistration_ = null;
        } else {
          movieregistration_ = null;
          movieregistrationBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.internal_static_com_ayon_movieservice_movieregistration_MovieRegistered_descriptor;
      }

      public com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered getDefaultInstanceForType() {
        return com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered.getDefaultInstance();
      }

      public com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered build() {
        com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered buildPartial() {
        com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered result = new com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered(this);
        if (movieregistrationBuilder_ == null) {
          result.movieregistration_ = movieregistration_;
        } else {
          result.movieregistration_ = movieregistrationBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered) {
          return mergeFrom((com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered other) {
        if (other == com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered.getDefaultInstance()) return this;
        if (other.hasMovieregistration()) {
          mergeMovieregistration(other.getMovieregistration());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration movieregistration_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration, com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration.Builder, com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistrationOrBuilder> movieregistrationBuilder_;
      /**
       * <code>.com.ayon.movieservice.movieregistration.MovieRegistration movieregistration = 1;</code>
       */
      public boolean hasMovieregistration() {
        return movieregistrationBuilder_ != null || movieregistration_ != null;
      }
      /**
       * <code>.com.ayon.movieservice.movieregistration.MovieRegistration movieregistration = 1;</code>
       */
      public com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration getMovieregistration() {
        if (movieregistrationBuilder_ == null) {
          return movieregistration_ == null ? com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration.getDefaultInstance() : movieregistration_;
        } else {
          return movieregistrationBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.ayon.movieservice.movieregistration.MovieRegistration movieregistration = 1;</code>
       */
      public Builder setMovieregistration(com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration value) {
        if (movieregistrationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          movieregistration_ = value;
          onChanged();
        } else {
          movieregistrationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.ayon.movieservice.movieregistration.MovieRegistration movieregistration = 1;</code>
       */
      public Builder setMovieregistration(
          com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration.Builder builderForValue) {
        if (movieregistrationBuilder_ == null) {
          movieregistration_ = builderForValue.build();
          onChanged();
        } else {
          movieregistrationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.ayon.movieservice.movieregistration.MovieRegistration movieregistration = 1;</code>
       */
      public Builder mergeMovieregistration(com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration value) {
        if (movieregistrationBuilder_ == null) {
          if (movieregistration_ != null) {
            movieregistration_ =
              com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration.newBuilder(movieregistration_).mergeFrom(value).buildPartial();
          } else {
            movieregistration_ = value;
          }
          onChanged();
        } else {
          movieregistrationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.ayon.movieservice.movieregistration.MovieRegistration movieregistration = 1;</code>
       */
      public Builder clearMovieregistration() {
        if (movieregistrationBuilder_ == null) {
          movieregistration_ = null;
          onChanged();
        } else {
          movieregistration_ = null;
          movieregistrationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.ayon.movieservice.movieregistration.MovieRegistration movieregistration = 1;</code>
       */
      public com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration.Builder getMovieregistrationBuilder() {
        
        onChanged();
        return getMovieregistrationFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.ayon.movieservice.movieregistration.MovieRegistration movieregistration = 1;</code>
       */
      public com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistrationOrBuilder getMovieregistrationOrBuilder() {
        if (movieregistrationBuilder_ != null) {
          return movieregistrationBuilder_.getMessageOrBuilder();
        } else {
          return movieregistration_ == null ?
              com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration.getDefaultInstance() : movieregistration_;
        }
      }
      /**
       * <code>.com.ayon.movieservice.movieregistration.MovieRegistration movieregistration = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration, com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration.Builder, com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistrationOrBuilder> 
          getMovieregistrationFieldBuilder() {
        if (movieregistrationBuilder_ == null) {
          movieregistrationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration, com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistration.Builder, com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistrationOrBuilder>(
                  getMovieregistration(),
                  getParentForChildren(),
                  isClean());
          movieregistration_ = null;
        }
        return movieregistrationBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.ayon.movieservice.movieregistration.MovieRegistered)
    }

    // @@protoc_insertion_point(class_scope:com.ayon.movieservice.movieregistration.MovieRegistered)
    private static final com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered();
    }

    public static com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MovieRegistered>
        PARSER = new com.google.protobuf.AbstractParser<MovieRegistered>() {
      public MovieRegistered parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MovieRegistered(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MovieRegistered> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MovieRegistered> getParserForType() {
      return PARSER;
    }

    public com.ayon.movieservice.movieregistration.MovieRegistrationDatamodel.MovieRegistered getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ayon_movieservice_movieregistration_MovieRegistration_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ayon_movieservice_movieregistration_MovieRegistration_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ayon_movieservice_movieregistration_MovieRegistered_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ayon_movieservice_movieregistration_MovieRegistered_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017datamodel.proto\022\'com.ayon.movieservice" +
      ".movieregistration\"m\n\021MovieRegistration\022" +
      "\n\n\002id\030\001 \001(\t\022\016\n\006imdbId\030\002 \001(\t\022\026\n\016available" +
      "Seats\030\003 \001(\005\022\020\n\010screenId\030\004 \001(\t\022\022\n\nmovieTi" +
      "tle\030\005 \001(\t\"h\n\017MovieRegistered\022U\n\021moviereg" +
      "istration\030\001 \001(\0132:.com.ayon.movieservice." +
      "movieregistration.MovieRegistrationB\036B\032M" +
      "ovieRegistrationDatamodelH\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ayon_movieservice_movieregistration_MovieRegistration_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ayon_movieservice_movieregistration_MovieRegistration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ayon_movieservice_movieregistration_MovieRegistration_descriptor,
        new java.lang.String[] { "Id", "ImdbId", "AvailableSeats", "ScreenId", "MovieTitle", });
    internal_static_com_ayon_movieservice_movieregistration_MovieRegistered_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ayon_movieservice_movieregistration_MovieRegistered_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ayon_movieservice_movieregistration_MovieRegistered_descriptor,
        new java.lang.String[] { "Movieregistration", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
