// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datamodel.proto

package com.ayon.movieservice.moviereservation;

public final class MovieReservationDatamodel {
  private MovieReservationDatamodel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MovieReservationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ayon.movieservice.moviereservation.MovieReservation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string imdbId = 2;</code>
     */
    java.lang.String getImdbId();
    /**
     * <code>string imdbId = 2;</code>
     */
    com.google.protobuf.ByteString
        getImdbIdBytes();

    /**
     * <code>string screenId = 3;</code>
     */
    java.lang.String getScreenId();
    /**
     * <code>string screenId = 3;</code>
     */
    com.google.protobuf.ByteString
        getScreenIdBytes();

    /**
     * <code>string movieTitle = 4;</code>
     */
    java.lang.String getMovieTitle();
    /**
     * <code>string movieTitle = 4;</code>
     */
    com.google.protobuf.ByteString
        getMovieTitleBytes();

    /**
     * <code>int32 availableSeats = 5;</code>
     */
    int getAvailableSeats();

    /**
     * <code>int32 reservedSeats = 6;</code>
     */
    int getReservedSeats();
  }
  /**
   * Protobuf type {@code com.ayon.movieservice.moviereservation.MovieReservation}
   */
  public  static final class MovieReservation extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ayon.movieservice.moviereservation.MovieReservation)
      MovieReservationOrBuilder {
    // Use MovieReservation.newBuilder() to construct.
    private MovieReservation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MovieReservation() {
      id_ = "";
      imdbId_ = "";
      screenId_ = "";
      movieTitle_ = "";
      availableSeats_ = 0;
      reservedSeats_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MovieReservation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              imdbId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              screenId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              movieTitle_ = s;
              break;
            }
            case 40: {

              availableSeats_ = input.readInt32();
              break;
            }
            case 48: {

              reservedSeats_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ayon.movieservice.moviereservation.MovieReservationDatamodel.internal_static_com_ayon_movieservice_moviereservation_MovieReservation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ayon.movieservice.moviereservation.MovieReservationDatamodel.internal_static_com_ayon_movieservice_moviereservation_MovieReservation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation.class, com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMDBID_FIELD_NUMBER = 2;
    private volatile java.lang.Object imdbId_;
    /**
     * <code>string imdbId = 2;</code>
     */
    public java.lang.String getImdbId() {
      java.lang.Object ref = imdbId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imdbId_ = s;
        return s;
      }
    }
    /**
     * <code>string imdbId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getImdbIdBytes() {
      java.lang.Object ref = imdbId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imdbId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCREENID_FIELD_NUMBER = 3;
    private volatile java.lang.Object screenId_;
    /**
     * <code>string screenId = 3;</code>
     */
    public java.lang.String getScreenId() {
      java.lang.Object ref = screenId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        screenId_ = s;
        return s;
      }
    }
    /**
     * <code>string screenId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getScreenIdBytes() {
      java.lang.Object ref = screenId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        screenId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MOVIETITLE_FIELD_NUMBER = 4;
    private volatile java.lang.Object movieTitle_;
    /**
     * <code>string movieTitle = 4;</code>
     */
    public java.lang.String getMovieTitle() {
      java.lang.Object ref = movieTitle_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        movieTitle_ = s;
        return s;
      }
    }
    /**
     * <code>string movieTitle = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMovieTitleBytes() {
      java.lang.Object ref = movieTitle_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        movieTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AVAILABLESEATS_FIELD_NUMBER = 5;
    private int availableSeats_;
    /**
     * <code>int32 availableSeats = 5;</code>
     */
    public int getAvailableSeats() {
      return availableSeats_;
    }

    public static final int RESERVEDSEATS_FIELD_NUMBER = 6;
    private int reservedSeats_;
    /**
     * <code>int32 reservedSeats = 6;</code>
     */
    public int getReservedSeats() {
      return reservedSeats_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getImdbIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, imdbId_);
      }
      if (!getScreenIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, screenId_);
      }
      if (!getMovieTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, movieTitle_);
      }
      if (availableSeats_ != 0) {
        output.writeInt32(5, availableSeats_);
      }
      if (reservedSeats_ != 0) {
        output.writeInt32(6, reservedSeats_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getImdbIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, imdbId_);
      }
      if (!getScreenIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, screenId_);
      }
      if (!getMovieTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, movieTitle_);
      }
      if (availableSeats_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, availableSeats_);
      }
      if (reservedSeats_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, reservedSeats_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation)) {
        return super.equals(obj);
      }
      com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation other = (com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getImdbId()
          .equals(other.getImdbId());
      result = result && getScreenId()
          .equals(other.getScreenId());
      result = result && getMovieTitle()
          .equals(other.getMovieTitle());
      result = result && (getAvailableSeats()
          == other.getAvailableSeats());
      result = result && (getReservedSeats()
          == other.getReservedSeats());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + IMDBID_FIELD_NUMBER;
      hash = (53 * hash) + getImdbId().hashCode();
      hash = (37 * hash) + SCREENID_FIELD_NUMBER;
      hash = (53 * hash) + getScreenId().hashCode();
      hash = (37 * hash) + MOVIETITLE_FIELD_NUMBER;
      hash = (53 * hash) + getMovieTitle().hashCode();
      hash = (37 * hash) + AVAILABLESEATS_FIELD_NUMBER;
      hash = (53 * hash) + getAvailableSeats();
      hash = (37 * hash) + RESERVEDSEATS_FIELD_NUMBER;
      hash = (53 * hash) + getReservedSeats();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ayon.movieservice.moviereservation.MovieReservation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ayon.movieservice.moviereservation.MovieReservation)
        com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ayon.movieservice.moviereservation.MovieReservationDatamodel.internal_static_com_ayon_movieservice_moviereservation_MovieReservation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ayon.movieservice.moviereservation.MovieReservationDatamodel.internal_static_com_ayon_movieservice_moviereservation_MovieReservation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation.class, com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation.Builder.class);
      }

      // Construct using com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        imdbId_ = "";

        screenId_ = "";

        movieTitle_ = "";

        availableSeats_ = 0;

        reservedSeats_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ayon.movieservice.moviereservation.MovieReservationDatamodel.internal_static_com_ayon_movieservice_moviereservation_MovieReservation_descriptor;
      }

      public com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation getDefaultInstanceForType() {
        return com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation.getDefaultInstance();
      }

      public com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation build() {
        com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation buildPartial() {
        com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation result = new com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation(this);
        result.id_ = id_;
        result.imdbId_ = imdbId_;
        result.screenId_ = screenId_;
        result.movieTitle_ = movieTitle_;
        result.availableSeats_ = availableSeats_;
        result.reservedSeats_ = reservedSeats_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation) {
          return mergeFrom((com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation other) {
        if (other == com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getImdbId().isEmpty()) {
          imdbId_ = other.imdbId_;
          onChanged();
        }
        if (!other.getScreenId().isEmpty()) {
          screenId_ = other.screenId_;
          onChanged();
        }
        if (!other.getMovieTitle().isEmpty()) {
          movieTitle_ = other.movieTitle_;
          onChanged();
        }
        if (other.getAvailableSeats() != 0) {
          setAvailableSeats(other.getAvailableSeats());
        }
        if (other.getReservedSeats() != 0) {
          setReservedSeats(other.getReservedSeats());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object imdbId_ = "";
      /**
       * <code>string imdbId = 2;</code>
       */
      public java.lang.String getImdbId() {
        java.lang.Object ref = imdbId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          imdbId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string imdbId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getImdbIdBytes() {
        java.lang.Object ref = imdbId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imdbId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string imdbId = 2;</code>
       */
      public Builder setImdbId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imdbId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string imdbId = 2;</code>
       */
      public Builder clearImdbId() {
        
        imdbId_ = getDefaultInstance().getImdbId();
        onChanged();
        return this;
      }
      /**
       * <code>string imdbId = 2;</code>
       */
      public Builder setImdbIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        imdbId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object screenId_ = "";
      /**
       * <code>string screenId = 3;</code>
       */
      public java.lang.String getScreenId() {
        java.lang.Object ref = screenId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          screenId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string screenId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getScreenIdBytes() {
        java.lang.Object ref = screenId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          screenId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string screenId = 3;</code>
       */
      public Builder setScreenId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        screenId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string screenId = 3;</code>
       */
      public Builder clearScreenId() {
        
        screenId_ = getDefaultInstance().getScreenId();
        onChanged();
        return this;
      }
      /**
       * <code>string screenId = 3;</code>
       */
      public Builder setScreenIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        screenId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object movieTitle_ = "";
      /**
       * <code>string movieTitle = 4;</code>
       */
      public java.lang.String getMovieTitle() {
        java.lang.Object ref = movieTitle_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          movieTitle_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string movieTitle = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMovieTitleBytes() {
        java.lang.Object ref = movieTitle_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          movieTitle_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string movieTitle = 4;</code>
       */
      public Builder setMovieTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        movieTitle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string movieTitle = 4;</code>
       */
      public Builder clearMovieTitle() {
        
        movieTitle_ = getDefaultInstance().getMovieTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string movieTitle = 4;</code>
       */
      public Builder setMovieTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        movieTitle_ = value;
        onChanged();
        return this;
      }

      private int availableSeats_ ;
      /**
       * <code>int32 availableSeats = 5;</code>
       */
      public int getAvailableSeats() {
        return availableSeats_;
      }
      /**
       * <code>int32 availableSeats = 5;</code>
       */
      public Builder setAvailableSeats(int value) {
        
        availableSeats_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 availableSeats = 5;</code>
       */
      public Builder clearAvailableSeats() {
        
        availableSeats_ = 0;
        onChanged();
        return this;
      }

      private int reservedSeats_ ;
      /**
       * <code>int32 reservedSeats = 6;</code>
       */
      public int getReservedSeats() {
        return reservedSeats_;
      }
      /**
       * <code>int32 reservedSeats = 6;</code>
       */
      public Builder setReservedSeats(int value) {
        
        reservedSeats_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 reservedSeats = 6;</code>
       */
      public Builder clearReservedSeats() {
        
        reservedSeats_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.ayon.movieservice.moviereservation.MovieReservation)
    }

    // @@protoc_insertion_point(class_scope:com.ayon.movieservice.moviereservation.MovieReservation)
    private static final com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation();
    }

    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MovieReservation>
        PARSER = new com.google.protobuf.AbstractParser<MovieReservation>() {
      public MovieReservation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MovieReservation(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MovieReservation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MovieReservation> getParserForType() {
      return PARSER;
    }

    public com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MovieReservedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ayon.movieservice.moviereservation.MovieReserved)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.ayon.movieservice.moviereservation.MovieReservation moviereservation = 1;</code>
     */
    boolean hasMoviereservation();
    /**
     * <code>.com.ayon.movieservice.moviereservation.MovieReservation moviereservation = 1;</code>
     */
    com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation getMoviereservation();
    /**
     * <code>.com.ayon.movieservice.moviereservation.MovieReservation moviereservation = 1;</code>
     */
    com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservationOrBuilder getMoviereservationOrBuilder();
  }
  /**
   * Protobuf type {@code com.ayon.movieservice.moviereservation.MovieReserved}
   */
  public  static final class MovieReserved extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ayon.movieservice.moviereservation.MovieReserved)
      MovieReservedOrBuilder {
    // Use MovieReserved.newBuilder() to construct.
    private MovieReserved(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MovieReserved() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MovieReserved(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation.Builder subBuilder = null;
              if (moviereservation_ != null) {
                subBuilder = moviereservation_.toBuilder();
              }
              moviereservation_ = input.readMessage(com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(moviereservation_);
                moviereservation_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ayon.movieservice.moviereservation.MovieReservationDatamodel.internal_static_com_ayon_movieservice_moviereservation_MovieReserved_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ayon.movieservice.moviereservation.MovieReservationDatamodel.internal_static_com_ayon_movieservice_moviereservation_MovieReserved_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved.class, com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved.Builder.class);
    }

    public static final int MOVIERESERVATION_FIELD_NUMBER = 1;
    private com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation moviereservation_;
    /**
     * <code>.com.ayon.movieservice.moviereservation.MovieReservation moviereservation = 1;</code>
     */
    public boolean hasMoviereservation() {
      return moviereservation_ != null;
    }
    /**
     * <code>.com.ayon.movieservice.moviereservation.MovieReservation moviereservation = 1;</code>
     */
    public com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation getMoviereservation() {
      return moviereservation_ == null ? com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation.getDefaultInstance() : moviereservation_;
    }
    /**
     * <code>.com.ayon.movieservice.moviereservation.MovieReservation moviereservation = 1;</code>
     */
    public com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservationOrBuilder getMoviereservationOrBuilder() {
      return getMoviereservation();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (moviereservation_ != null) {
        output.writeMessage(1, getMoviereservation());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (moviereservation_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMoviereservation());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved)) {
        return super.equals(obj);
      }
      com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved other = (com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved) obj;

      boolean result = true;
      result = result && (hasMoviereservation() == other.hasMoviereservation());
      if (hasMoviereservation()) {
        result = result && getMoviereservation()
            .equals(other.getMoviereservation());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMoviereservation()) {
        hash = (37 * hash) + MOVIERESERVATION_FIELD_NUMBER;
        hash = (53 * hash) + getMoviereservation().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ayon.movieservice.moviereservation.MovieReserved}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ayon.movieservice.moviereservation.MovieReserved)
        com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ayon.movieservice.moviereservation.MovieReservationDatamodel.internal_static_com_ayon_movieservice_moviereservation_MovieReserved_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ayon.movieservice.moviereservation.MovieReservationDatamodel.internal_static_com_ayon_movieservice_moviereservation_MovieReserved_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved.class, com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved.Builder.class);
      }

      // Construct using com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (moviereservationBuilder_ == null) {
          moviereservation_ = null;
        } else {
          moviereservation_ = null;
          moviereservationBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ayon.movieservice.moviereservation.MovieReservationDatamodel.internal_static_com_ayon_movieservice_moviereservation_MovieReserved_descriptor;
      }

      public com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved getDefaultInstanceForType() {
        return com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved.getDefaultInstance();
      }

      public com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved build() {
        com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved buildPartial() {
        com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved result = new com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved(this);
        if (moviereservationBuilder_ == null) {
          result.moviereservation_ = moviereservation_;
        } else {
          result.moviereservation_ = moviereservationBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved) {
          return mergeFrom((com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved other) {
        if (other == com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved.getDefaultInstance()) return this;
        if (other.hasMoviereservation()) {
          mergeMoviereservation(other.getMoviereservation());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation moviereservation_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation, com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation.Builder, com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservationOrBuilder> moviereservationBuilder_;
      /**
       * <code>.com.ayon.movieservice.moviereservation.MovieReservation moviereservation = 1;</code>
       */
      public boolean hasMoviereservation() {
        return moviereservationBuilder_ != null || moviereservation_ != null;
      }
      /**
       * <code>.com.ayon.movieservice.moviereservation.MovieReservation moviereservation = 1;</code>
       */
      public com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation getMoviereservation() {
        if (moviereservationBuilder_ == null) {
          return moviereservation_ == null ? com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation.getDefaultInstance() : moviereservation_;
        } else {
          return moviereservationBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.ayon.movieservice.moviereservation.MovieReservation moviereservation = 1;</code>
       */
      public Builder setMoviereservation(com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation value) {
        if (moviereservationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          moviereservation_ = value;
          onChanged();
        } else {
          moviereservationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.ayon.movieservice.moviereservation.MovieReservation moviereservation = 1;</code>
       */
      public Builder setMoviereservation(
          com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation.Builder builderForValue) {
        if (moviereservationBuilder_ == null) {
          moviereservation_ = builderForValue.build();
          onChanged();
        } else {
          moviereservationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.ayon.movieservice.moviereservation.MovieReservation moviereservation = 1;</code>
       */
      public Builder mergeMoviereservation(com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation value) {
        if (moviereservationBuilder_ == null) {
          if (moviereservation_ != null) {
            moviereservation_ =
              com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation.newBuilder(moviereservation_).mergeFrom(value).buildPartial();
          } else {
            moviereservation_ = value;
          }
          onChanged();
        } else {
          moviereservationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.ayon.movieservice.moviereservation.MovieReservation moviereservation = 1;</code>
       */
      public Builder clearMoviereservation() {
        if (moviereservationBuilder_ == null) {
          moviereservation_ = null;
          onChanged();
        } else {
          moviereservation_ = null;
          moviereservationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.ayon.movieservice.moviereservation.MovieReservation moviereservation = 1;</code>
       */
      public com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation.Builder getMoviereservationBuilder() {
        
        onChanged();
        return getMoviereservationFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.ayon.movieservice.moviereservation.MovieReservation moviereservation = 1;</code>
       */
      public com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservationOrBuilder getMoviereservationOrBuilder() {
        if (moviereservationBuilder_ != null) {
          return moviereservationBuilder_.getMessageOrBuilder();
        } else {
          return moviereservation_ == null ?
              com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation.getDefaultInstance() : moviereservation_;
        }
      }
      /**
       * <code>.com.ayon.movieservice.moviereservation.MovieReservation moviereservation = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation, com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation.Builder, com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservationOrBuilder> 
          getMoviereservationFieldBuilder() {
        if (moviereservationBuilder_ == null) {
          moviereservationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation, com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservation.Builder, com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReservationOrBuilder>(
                  getMoviereservation(),
                  getParentForChildren(),
                  isClean());
          moviereservation_ = null;
        }
        return moviereservationBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.ayon.movieservice.moviereservation.MovieReserved)
    }

    // @@protoc_insertion_point(class_scope:com.ayon.movieservice.moviereservation.MovieReserved)
    private static final com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved();
    }

    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MovieReserved>
        PARSER = new com.google.protobuf.AbstractParser<MovieReserved>() {
      public MovieReserved parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MovieReserved(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MovieReserved> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MovieReserved> getParserForType() {
      return PARSER;
    }

    public com.ayon.movieservice.moviereservation.MovieReservationDatamodel.MovieReserved getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SeatReservedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ayon.movieservice.moviereservation.SeatReserved)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 seatCount = 1;</code>
     */
    int getSeatCount();
  }
  /**
   * Protobuf type {@code com.ayon.movieservice.moviereservation.SeatReserved}
   */
  public  static final class SeatReserved extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ayon.movieservice.moviereservation.SeatReserved)
      SeatReservedOrBuilder {
    // Use SeatReserved.newBuilder() to construct.
    private SeatReserved(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SeatReserved() {
      seatCount_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SeatReserved(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              seatCount_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ayon.movieservice.moviereservation.MovieReservationDatamodel.internal_static_com_ayon_movieservice_moviereservation_SeatReserved_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ayon.movieservice.moviereservation.MovieReservationDatamodel.internal_static_com_ayon_movieservice_moviereservation_SeatReserved_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved.class, com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved.Builder.class);
    }

    public static final int SEATCOUNT_FIELD_NUMBER = 1;
    private int seatCount_;
    /**
     * <code>int32 seatCount = 1;</code>
     */
    public int getSeatCount() {
      return seatCount_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (seatCount_ != 0) {
        output.writeInt32(1, seatCount_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (seatCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, seatCount_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved)) {
        return super.equals(obj);
      }
      com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved other = (com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved) obj;

      boolean result = true;
      result = result && (getSeatCount()
          == other.getSeatCount());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SEATCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getSeatCount();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ayon.movieservice.moviereservation.SeatReserved}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ayon.movieservice.moviereservation.SeatReserved)
        com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReservedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ayon.movieservice.moviereservation.MovieReservationDatamodel.internal_static_com_ayon_movieservice_moviereservation_SeatReserved_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ayon.movieservice.moviereservation.MovieReservationDatamodel.internal_static_com_ayon_movieservice_moviereservation_SeatReserved_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved.class, com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved.Builder.class);
      }

      // Construct using com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        seatCount_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ayon.movieservice.moviereservation.MovieReservationDatamodel.internal_static_com_ayon_movieservice_moviereservation_SeatReserved_descriptor;
      }

      public com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved getDefaultInstanceForType() {
        return com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved.getDefaultInstance();
      }

      public com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved build() {
        com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved buildPartial() {
        com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved result = new com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved(this);
        result.seatCount_ = seatCount_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved) {
          return mergeFrom((com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved other) {
        if (other == com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved.getDefaultInstance()) return this;
        if (other.getSeatCount() != 0) {
          setSeatCount(other.getSeatCount());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int seatCount_ ;
      /**
       * <code>int32 seatCount = 1;</code>
       */
      public int getSeatCount() {
        return seatCount_;
      }
      /**
       * <code>int32 seatCount = 1;</code>
       */
      public Builder setSeatCount(int value) {
        
        seatCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 seatCount = 1;</code>
       */
      public Builder clearSeatCount() {
        
        seatCount_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.ayon.movieservice.moviereservation.SeatReserved)
    }

    // @@protoc_insertion_point(class_scope:com.ayon.movieservice.moviereservation.SeatReserved)
    private static final com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved();
    }

    public static com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SeatReserved>
        PARSER = new com.google.protobuf.AbstractParser<SeatReserved>() {
      public SeatReserved parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SeatReserved(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SeatReserved> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SeatReserved> getParserForType() {
      return PARSER;
    }

    public com.ayon.movieservice.moviereservation.MovieReservationDatamodel.SeatReserved getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ayon_movieservice_moviereservation_MovieReservation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ayon_movieservice_moviereservation_MovieReservation_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ayon_movieservice_moviereservation_MovieReserved_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ayon_movieservice_moviereservation_MovieReserved_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ayon_movieservice_moviereservation_SeatReserved_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ayon_movieservice_moviereservation_SeatReserved_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017datamodel.proto\022&com.ayon.movieservice" +
      ".moviereservation\"\203\001\n\020MovieReservation\022\n" +
      "\n\002id\030\001 \001(\t\022\016\n\006imdbId\030\002 \001(\t\022\020\n\010screenId\030\003" +
      " \001(\t\022\022\n\nmovieTitle\030\004 \001(\t\022\026\n\016availableSea" +
      "ts\030\005 \001(\005\022\025\n\rreservedSeats\030\006 \001(\005\"c\n\rMovie" +
      "Reserved\022R\n\020moviereservation\030\001 \001(\01328.com" +
      ".ayon.movieservice.moviereservation.Movi" +
      "eReservation\"!\n\014SeatReserved\022\021\n\tseatCoun" +
      "t\030\001 \001(\005B\035B\031MovieReservationDatamodelH\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ayon_movieservice_moviereservation_MovieReservation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ayon_movieservice_moviereservation_MovieReservation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ayon_movieservice_moviereservation_MovieReservation_descriptor,
        new java.lang.String[] { "Id", "ImdbId", "ScreenId", "MovieTitle", "AvailableSeats", "ReservedSeats", });
    internal_static_com_ayon_movieservice_moviereservation_MovieReserved_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ayon_movieservice_moviereservation_MovieReserved_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ayon_movieservice_moviereservation_MovieReserved_descriptor,
        new java.lang.String[] { "Moviereservation", });
    internal_static_com_ayon_movieservice_moviereservation_SeatReserved_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_ayon_movieservice_moviereservation_SeatReserved_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ayon_movieservice_moviereservation_SeatReserved_descriptor,
        new java.lang.String[] { "SeatCount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
