version: '2'

services:
  cassandra:
    image: cassandra:3
    container_name: cassandra
    ports:
      - "7000:7000"
      - "9042:9042"
    environment:
      - "CASSANDRA_CLUSTER_NAME=OUR_DOCKERIZED_CASSANDRA_SINGLE_NODE_CLUSTER"

  elasticsearch:
    image: elasticsearch:2.4.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "TZ=Asia/Calcutta"
    volumes:
      - "./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"

  moviebookingstore:
    image: server:latest
    container_name: moviebookingstore
    environment:
      - "TZ=Asia/Calcutta"
      - "CASSANDRA_HOST=cassandra"
      - "ELASTICSEARCH_HOST=elasticsearch"
      - "PERSISTENT_ENTITY_TIMEOUT=10s"
    ports:
    - "8080:8080"
